,
            { "caption": "-" },
            { "command": "", "caption": "Rename Local Variable - Diff" },
            { "command": "", "caption": "Rename Local Variable - Patch" },
            { "caption": "-" },
            { "command": "", "caption": "Optimize use statements - Diff" },
            { "command": "", "caption": "Optimize use statements - Patch" },
            { "caption": "-" },
            { "command": "", "caption": "Convert Local Variable to Instance Variable - Diff" },
            { "command": "", "caption": "Convert Local Variable to Instance Variable - Patch" },
            { "caption": "-" },
            { "command": "", "caption": "Convert Magic Value to Constant - Diff" },
            { "command": "", "caption": "Convert Magic Value to Constant - Patch" },
            { "caption": "-" },
            { "command": "", "caption": "Rename Method - Diff" },
            { "command": "", "caption": "Rename Method - Patch" },
            { "caption": "-" },
            { "command": "", "caption": "Rename Instance Variable - Diff" },
            { "command": "", "caption": "Rename Instance Variable - Patch" },
            { "caption": "-" },
            { "command": "", "caption": "Rename Class - Diff" },
            { "command": "", "caption": "Rename Class - Patch" },
            { "caption": "-" },
            { "command": "", "caption": "Rename Namespace - Diff" },
            { "command": "", "caption": "Rename Namespace - Patch" }